name: scanpy-dev
channels:
  - anaconda
  - bioconda
  - conda-forge
dependencies:
  - python=3.6
  - scanpy
  - matplotlib=3.0.2
  - scipy=1.4
  - scikit-learn=0.22
  - h5py=2.7
  - leidenalg
  - seaborn=0.10
  - umap-learn=0.3
  - memory_profiler
  - pytest
  - ipykernel
