{% set name = "sc3s" %}
{% set version = "0.0.1-dev1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python>=3.6 
  run:
    - numpy>=1.19.2,<2 
    - pandas>=1.2.2
    - python>=3.6
    - scikit-learn>=0.23.2
    - scanpy>=1.7.0
    - six>=1.15.0
    - setuptools>=52.0.0
    - joblib>=1.0.0
    - mkl-service>=2.3.0
    - h5py >=3.1.0
    - seaborn
    - scipy
    - python-dateutil >=2.8.1
    - openssl >=1.0.1

about:
  home: "https://github.com/pittachalk/sc3s"
  license: BSD
  license_family: BSD
  license_file: 
  summary: "Python Single Cell Consensus Clustering"
  doc_url: 
  dev_url: 
