name: sdist

on:
  release:
    types:
      - created
jobs:
  sdists:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install --upgrade setuptools wheel
    - name: Build source distribution
      run: python setup.py sdist
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
